//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSfonacotDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestacionesSuperv_Sucursales
    {
        public int Idcontestacion { get; set; }
        public Nullable<int> Idsupervision { get; set; }
        public string Inmueble { get; set; }
        public string Gestion_direccion { get; set; }
        public string Originacion { get; set; }
        public string Tarjetas_transfer { get; set; }
        public string Credito { get; set; }
        public string Utys { get; set; }
        public string Promocionales { get; set; }
        public string Cobranza { get; set; }
        public string Fondofijo { get; set; }
        public string AcuerdosCompromisos { get; set; }
        public string NoOficio { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<System.DateTime> FechaCreacionContest { get; set; }
        public Nullable<int> Idusuariocreador { get; set; }
    
        public virtual HistorialSupervisiones HistorialSupervisiones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
