//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSfonacotDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_de_Supervisiones
    {
        public int IdSupervisiones { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string NoSupervision { get; set; }
        public Nullable<System.DateTime> FechaSupervision { get; set; }
        public string AfiliacionOtorgamientoCredito { get; set; }
        public string ActividadesPromocionAfiliaciónCT { get; set; }
        public string ProcesoCobranza { get; set; }
        public string Revisión_de_UTYS { get; set; }
        public string Situaciones_de_Orden_General_e_Infraestructura { get; set; }
        public string AcuerdosCompromisos { get; set; }
        public string No_de_Respuesta_Supervision { get; set; }
        public Nullable<System.DateTime> FechaRespuestaSupervision { get; set; }
        public string Seguimiento_a_la_Supervisión { get; set; }
        public string Respuesta_Supervision { get; set; }
        public Nullable<bool> Solventada { get; set; }
        public Nullable<int> IdSupervisor1 { get; set; }
        public Nullable<int> IdSupervisor2 { get; set; }
        public string NoOficio { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
