//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDSfonacotDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento_RespuestaSucursales
    {
        public int IdRespuesta { get; set; }
        public Nullable<int> IdSupervision { get; set; }
        public string OficioRespuesta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<bool> Solventada { get; set; }
        public Nullable<int> IdusuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaRespCreacion { get; set; }
    
        public virtual HistorialSupervisiones HistorialSupervisiones { get; set; }
    }
}
